In [1]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model

In [3]:
df=pd.read_csv('test_scores.csv')
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [4]:
a=df.math
b=df.cs
a, b

(0    92
 1    56
 2    88
 3    70
 4    80
 5    49
 6    65
 7    35
 8    66
 9    67
 Name: math, dtype: int64,
 0    98
 1    68
 2    81
 3    80
 4    83
 5    52
 6    66
 7    30
 8    68
 9    73
 Name: cs, dtype: int64)

In [5]:
x=np.array(list(a))
x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67])

In [6]:
y=np.array(list(b))
y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73])

In [15]:
def gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 100000
    n = len(x)
    learning_rate = 0.0002
    cost_previous=0

    for i in range(iterations):
        y_predicted = m_curr*x+b_curr
        
        md = -(2/n)*sum(x*(y-y_predicted))
        bd = -(2/n)*sum(y-y_predicted)

        cost = (1/n)*sum([val**2 for val in (y-y_predicted)])
        
        m_curr = m_curr-learning_rate*md
        b_curr = b_curr-learning_rate*bd

        if math.isclose(cost, cost_previous, rel_tol=1e-20):
            break
        cost_previous = cost
        
        print("m {}, b {}, cost {}, iteration {}".format(m_curr, b_curr, cost, i))  
        # return m_curr, b_curr

In [56]:
coefficient, intercept = gradient_descent(x,y)
coefficient, intercept

(np.float64(0.09891800000000002), np.float64(0.0013980000000000002))

In [50]:
reg=linear_model.LinearRegression()
reg.fit(x.reshape(-1,1), y)

LinearRegression()

In [51]:
reg.coef_

array([1.01773624])

In [52]:
reg.intercept_

np.float64(1.9152193111569176)